on: 
  push:
    branches: 
      - develop
name: 🚀 Deploy website on to Staging
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 95.217.226.51
        username: ixpens02@ixpensa.com
        password: ${{ secrets.password }}
        # server-dir : /IxpensaApp/developpement/back/front/
        server-dir : /IxpensaApp/developpement/fullstack/
